# Generated by Django 5.2.8 on 2025-11-21 13:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('sno', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sno', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='New', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('so_no', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice', models.CharField(blank=True, max_length=100)),
                ('remark', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('lead_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('task_type', models.CharField(default='Follow Up', max_length=100)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('follow_up_count', models.IntegerField(default=0)),
                ('priority', models.CharField(default='Medium', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('gem_id', models.CharField(blank=True, max_length=100)),
                ('gem_password', models.CharField(blank=True, max_length=100)),
                ('task_name', models.TextField(blank=True)),
                ('priority', models.CharField(default='Medium', max_length=50)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('machine', models.CharField(blank=True, max_length=200)),
                ('serial', models.CharField(blank=True, max_length=100)),
                ('warranty', models.DateField(blank=True, null=True)),
                ('service_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('bid_no', models.CharField(max_length=100)),
                ('item', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Draft', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
