# Generated by Django 5.2.8 on 2025-12-06 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
