# Generated by Django 5.2.8 on 2025-12-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
