# Generated by Django 5.2.8 on 2026-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
